services:
  mqtt-broker:
    container_name: ryde-notification-mqtt
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    networks:
      - ryde-network
  notification-service:
    build: 
      context: .
    ports:
      - "8083:8083"
    depends_on:
      - mqtt-broker
    networks:
      - ryde-network

networks:
  ryde-network:
    external: true
