services:
  mqtt-broker:
    container_name: mqtt-location
    image: toke/mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      
  ryde:
    build: .
    container_name: ryde-location
    ports:
      - "8083:8083"
    depends_on:
      - mqtt-broker
