services:
  mqtt-broker:
    container_name: ryde-notification-mqtt
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    networks:
      - internal
      - external
  notification-service:
    build: 
      context: .
    depends_on:
      - mqtt-broker
    networks:
      - internal
