services:
  mongo:
    container_name: mongo-driver
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017"
      
  ryde:
    build: .
    container_name: ryde-driver
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
