services:
  driver-service:
    build: 
      context: .
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017/driver_db
      - REDIS_URL=redis://redis:6379
    networks:
      - external
