services:
  trip-service:
    build: 
      context: .
    ports:
      - "8084:8084"
    environment:
      - MONGO_URI=mongodb://mongo:27017/trip_db
      - REDIS_URL=redis://redis:6379
    networks:
      - internal
      - external
