services:
  user-service:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_db 
    networks:
      - ryde-network

networks:
  ryde-network:
    external: true
