services:
  mongo:
    container_name: mongo-user
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
      
  ryde:
    build: .
    container_name: ryde-user
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
